plugins {
    id 'java'
}

repositories {
    mavenCentral()
    maven {
        url = 'https://repo.runelite.net'
        content {
            includeGroupByRegex("net\\.runelite.*")
        }
    }
    mavenLocal()
}

def runeLiteVersion = 'latest.release'

dependencies {
    compileOnly group: 'net.runelite', name: 'client', version: runeLiteVersion

    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    testImplementation 'junit:junit:4.13.2'
    testImplementation group: 'net.runelite', name: 'client', version: runeLiteVersion
    testImplementation group: 'net.runelite', name: 'jshell', version: runeLiteVersion
}

group = 'com.grandexchangepanelplus'
version = '1.0.0'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
    options.release.set(11)
}

task run(type: JavaExec) {
    classpath = sourceSets.test.runtimeClasspath
    mainClass = 'com.grandexchangepanelplus.GrandExchangePanelPlusPluginTest'
    jvmArgs "-XX:HotswapAgent=fatjar", "-ea"
    if (project.hasProperty('runelite.home')) {
        jvmArgs "-Duser.home=${project.property('runelite.home')}"
    }
    args "--developer-mode", "--debug"
}
